name: Build Client

defaults:
  run:
    working-directory: ./client

on:
  push:
    branches: [main]
    paths:
      - client/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: set tag
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/koken-ldap-manager-client:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max